config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :carpets do
    resources :bookings
  end
  get '/profile', to: "pages#profile", as: "profile"
  root to: 'carpets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :carpet
end

app/models/carpet.rb
class Carpet < ApplicationRecord
  belongs_to :user
  validates :name, uniqueness: true, presence: true
  validates :price, presence: true
  validates :speed, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :passengers, presence: true, inclusion: { in: (0..50)}
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carpets
  has_many :bookings

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?

   # include Pundit

     # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!

  def create
    @booking = Booking.new(booking_param)
    @booking.user = current_user
    @booking.carpet = Carpet.find(params[:carpet_id])
    if @booking.save!
      flash[:notice] = "Booking confirmed"
      redirect_to profile_path
    else
      redirect_to carpet_path(@carpet)
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @bookings = Booking.all
    # authorize @carpet
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_param)
    redirect_to carpet_booking_path(@booking)
  end

   def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to carpet_bookings_path
  end

  private

  def booking_param
    params.require(:booking).permit(:user_id, :carpet_id, :startdate, :enddate)
  end
end

app/controllers/carpets_controller.rb
# require pickadate/picker
# require pickadate/picker.date
# require pickadate/picker.time

class CarpetsController < ApplicationController
  def index
    @carpets = Carpet.geocoded

    @markers = @carpets.map do |carpet|
      {
        lat: carpet.latitude,
        lng: carpet.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { carpet: carpet }),
        image_url: 'carpet.remote_photo_url'
      }
    end
  end

  def show
    find_carpet
    @booking = Booking.new
  end

  def new
    @carpet = Carpet.new
  end

  def create
    @carpet = Carpet.new(carpet_params)
    # @user = User.find(params[:user_id])
    @carpet.user = current_user
    if @carpet.save
      redirect_to carpet_path(@carpet)
    else
      render :new
    end
  end

  def edit
    find_carpet
  end

  def update
    @carpet = Carpet.find(params[:id])
    @carpet.update(carpet_params)
    redirect_to carpet_path(@carpet)
  end

  def destroy
    @carpet = Carpet.find(params[:id])
    @carpet.destroy
    redirect_to carpets_path
  end

  def datepicker_input(form, field)
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
  end

  private

  def carpet_params
    params.require(:carpet).permit(:name, :price, :speed, :description, :passengers, :address, :photo)
  end

  def find_carpet
    @carpet = Carpet.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def profile
    @bookings = current_user.bookings
    @listed_carpets = current_user.carpets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div>
  <%= simple_form_for([carpet, booking]) do |c| %>
    <%= c.label :startdate, "Start Date: " %>
    <%= c.input_field :startdate %>
    <%= c.label :enddate, "End Date: " %>
    <%= c.input_field :enddate %>
    <%= c.submit 'Save this Booking', class: "btn btn-success"%>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<%= render 'form', carpet: @booking.carpet, booking: @booking %>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>
<ol>
  <% @bookings.each do |b| %>
    <li>
      <h2>  <%= link_to b.carpet.name, carpet_booking_path(b.carpet, b) %></h2>
      <p><strong>Rental Start Date:</strong> <%= b.startdate.strftime('%Y-%m-%d') %></p>
      <p><strong>Rental End Date: </strong><%= b.enddate.strftime('%Y-%m-%d') %></p>
      <p><strong>Price Per Day: </strong><%= b.carpet.price %> Camels</p>

    </li>
  <% end %>
</ol>

app/views/bookings/show.html.erb
<h2>Name: <strong><%=  @booking.carpet.name %></strong></h2>
<p>Price in Camels: <strong><%= @booking.carpet.price %></strong></p>
<p>Description: <strong><%= @booking.carpet.description %></strong></p>
<p>Speed (km/min): <strong><%= @booking.carpet.speed %></strong></p>
<p>Number of supported passengers: <strong><%= @booking.carpet.passengers %></strong></p>
<p>Owner: <strong><%= @booking.carpet.user_id %></strong></p>
<p>Start Date: <strong><%= @booking.startdate %></strong></p>
<p>End Date: <strong><%= @booking.enddate %></strong></p>

<%= link_to 'Edit Booking', edit_carpet_booking_path(@booking.carpet, @booking), class: "btn btn-info" %>
<%= link_to 'Delete this Booking', carpet_booking_path(@booking.carpet, @booking), method: :delete, data: { confirm: "Are You Sure?"},class: "btn btn-warning" %>

app/views/carpets/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

<div class="new-carpet">
  <h3>Please Enter Your Carpet Information</h3>
  <%= simple_form_for @carpet do |c| %>

    <%= c.input :name, input_html: { class: "xyz"}  %>

    <%= c.input :price %>

    <%= c.input :speed %>
    <%= c.input :photo %>
    <%= c.input :photo_cache, as: :hidden %>

    <%= c.input :address %>

    <%= c.input :passengers %>

    <%= c.input :description %>
    <%= c.submit 'Save this Carpet', class: "btn-block"%>
  <% end %>
</div>




    </div>
  </div>
</div>

app/views/carpets/_info_window.html.erb
<div class="card-info-map" style="max-width: 12rem;">
  <%= link_to carpet_path(carpet) do %>
  <img src= "<%= cl_image_path carpet.photo, crop: :fill %>" class="card-img-map" alt="#">
  <% end %>
  <div class="card-body-map">
    <h2 class="card-title-map"><%= carpet.name %></h2>
    <p class="card-text-map">Location: <%= carpet.address %></p>
    <p class="card-text-map "><%= carpet.price %> <img src="https://image.flaticon.com/icons/svg/47/47030.svg" class="camel">/day  </p>
  </div>
</div>

app/views/carpets/edit.html.erb
<%= render 'form', carpet: @carpet %>

app/views/carpets/index.html.erb
<div class="text-center mx-2 my-2">
  <h5 class="m-3" id="index-title">Popular Carpets Today</h5>
  <div class="row mx-2 my-2">
    <div id="myCarousel" class="carousel slide col-12" data-ride="carousel">
     <div class="row">
         <a class="carousel-control-prev text-dark" href="#myCarousel" role="button" data-slide="prev">
           <span class="fa fa-chevron-left align-top" aria-hidden="true"></span>
         </a>
         <a class="carousel-control-next text-dark" href="#myCarousel" role="button" data-slide="next">
           <span class="fa fa-chevron-right align-top" aria-hidden="true"></span>
         </a>
         <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <div class="container">
            <div class="row">
             <% @carpets.in_groups_of(4, false).first.each do |carpet| %>
              <div class="col-md-3 col-sm-6 col-xs-12">
             <%= link_to carpet_path(carpet), class: "card carpet-card " do %>
             <%= cl_image_tag carpet.photo %>
             <p class="card-title"><strong><%= carpet.name %></strong></p>
             <div class="card-details">
              <p.small><%= carpet.description %></p>
            </div>
            <% end%>
              </div>
            <% end %>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="container">
          <div class="row">
           <% @carpets.in_groups_of(4, false).second.each do |carpet| %>
           <div class="col-md-3 col-sm-6 col-xs-12">
           <%= link_to carpet_path(carpet), class: "card carpet-card" do %>
           <%= cl_image_tag carpet.photo %>
           <p class="card-title"><strong><%= carpet.name %></strong></p>
           <div class="card-details">
            <p.small><%= carpet.description %></p>
          </div>
          <% end%>
             </div>
          <% end %>
        </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="container">
        <div class="row">
         <% @carpets.in_groups_of(4, false).third.each do |carpet| %>
         <div class="col-md-3 col-sm-6 col-xs-12">
         <%= link_to carpet_path(carpet), class: "card carpet-card" do %>
         <%= cl_image_tag carpet.photo %>
         <p class="card-title"><strong><%= carpet.name %></strong></p>
         <div class="card-details">
          <p.small> <%= carpet.description %></p>
        </div>
        <% end%>
      </div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>
</div>
  <div
  id="map"
  class="container-fluid offset-1.5 mt-5"
  style="width: 75%;
  height: 500px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>
</div>

app/views/carpets/new.html.erb
<%= render 'form', carpet: @carpet %>

app/views/carpets/show.html.erb
<div class="row">
  <div class="col-3"></div>
<div class="container carpet-show-contain row col-6">
  <div class="col-xs-7 margin-top-50">
    <div class="carpet-pic left-side">
      <%= cl_image_tag @carpet.photo, crop: :fill %>
    </div>


  </div>
  <div class="col-xs-5 product margin-top-50">
      <div class="row">
              <p id="heading-carpet"><%=  @carpet.name %></p>
      </div>
    <% if current_user.id == @carpet.user.id %>
      <div class="buttons">
           <td>
        <%= link_to edit_carpet_path(@carpet), class: 'btn btn-default' do %>
        <span class="fas fa-pencil-alt"></span>
        <% end %>
      </td>
      <td>
        <%= link_to carpet_path(@carpet), method: :delete, data: { confirm: "Are You Sure?"}, class: 'btn btn-default' do %>
        <span class="fas fa-trash"></span>
        <% end %>
      </td>
      </div>
    <% end %>

      <p id="carpet-price"> <%= @carpet.price %> Camels</p>
      <p class="desc "><%= @carpet.description %></p>
      <p class="desc fas fa-tachometer-alt">   <%= @carpet.speed %> km/min</p>
      <p class="desc fas fa-users">   <%= @carpet.passengers %></p>
      <p class="desc fas fa-map-marker-alt">    <%= @carpet.address %></p>
      <div class="Date left-side">
            <%= simple_form_for([@carpet, @booking]) do |c| %>
        <%= c.input :startdate, as: :string, required: false, input_html: {class: "datepicker", placeholder: "Select your Booking Dates"}, label: false %>

      </div>
  </div>
          <%= c.submit 'Book this Carpet', class: "btn btn-success book-btn"%>
        <% end %>
</div>
<div class="col-3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Carpet Connection</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Brawler&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
                                                            carpets#new

app/views/pages/profile.html.erb
<!-- link to take me to edit my profile / add a picture -->
<div class="header">
  <h1>
     <%= link_to "Edit My Profile", edit_user_registration_path %>
  </h1>

</div>


<!-- My bookings Section, link to carpets index if no booked carpets -->
<% if @bookings.length == 0 %>
  <%= link_to carpets_path do %>
    <p class="header">
      Book a Carpet NOW!
    </p>
  <% end %>
<% else %>
  <div class="header">
    <h1>Your Booked Carpets:</h1>
  </div>
  <div class="container">
    <div class="row space-between">
            <% @bookings.each do |booking|%>
  <%= link_to carpet_path(booking.carpet), class: "no-hover" do%>
    <div class="our-booking card-product">
      <% if booking.carpet.photo.file  %>
        <%= cl_image_tag booking.carpet.photo %>
        <% else %>
        <%= image_tag "supreme.jpg" %>
        <% end %>
        <div class="card-product-infos">
          <h2><%= booking.carpet.name %></h2>
          <p><%= booking.carpet.description.truncate(23) %></p>
          <div class="dates">
            <i class="fas fa-calendar-alt"></i>
            <% if booking.startdate %>
            <%= booking.startdate.strftime("%d / %m")   %> - <%= booking.enddate.strftime("%d / %m") %>
            <% end %>
          </div>
        </div>
    </div>
    <% end %>
  <% end %>
    </div>
  </div>
<% end %>
<!-- My listed carpets Section, link to list a carpet if no carpets listed -->
<% if @listed_carpets.length == 0 %>
  <%= link_to new_carpet_path do %>
    <p class="header">
      Add a carpet and fly with jesus!
    </p>
  <% end %>
<% else %>
  <div class="header">
    <h1>Your Listed Carpets:</h1>
  </div>
  <div class="container">
    <div class="row space-between">
    <% @listed_carpets.each do |carpet|%>
      <div class="d-flex mt-3 our-booking card-product">
        <%= cl_image_tag carpet.photo, class: "img"%>
        <div class = "details">
        <h4><%= carpet.name %></h4>
        <p><%= carpet.description %></p>
        <p><%= carpet.address %></p>
      </div>
        <div class="a">
          <%= link_to "Show carpet", carpet_path(carpet)%>
        </div>
      </div>
     <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <%= link_to "CARPETS FOR CAMELS", carpets_path, class: "navbar-brand"%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <% if signed_in? && !current_user.photo.filename.nil? %>
            <%= cl_image_tag current_user.photo, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% elsif signed_in? %>
            <%= image_tag "aladdin.jpg", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "All carpets", carpets_path, class: "dropdown-item" %>
            <%= link_to "Add new carpet", new_carpet_path, class: "dropdown-item" %>
            <%= link_to "My profile", profile_path, class: "dropdown-item" %>
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>